# Package

version       = "0.1.0"
author        = "George Lemon"
description   = "Auto-generated Nim clients for the PayPal REST APIs"
license       = "MIT"
srcDir        = "src"
installDirs   = @["deps", "paypal"]


# Dependencies

requires "nim >= 2.2.10"
requires "openparser"
requires "oauth2"
task test, "Run all tests":
  exec "nim r deps/subscriptions/tests/test_plans.nim"
  exec "nim r deps/subscriptions/tests/test_subscriptions.nim"
  exec "nim r deps/catalog/tests/test_products.nim"
  exec "nim r deps/orders/tests/test_externalcallback.nim"
  exec "nim r deps/orders/tests/test_orders.nim"
  exec "nim r deps/orders/tests/test_trackers.nim"
  exec "nim r deps/disputes/tests/test_disputes.nim"
  exec "nim r deps/disputes/tests/test_disputes_actions.nim"
  exec "nim r deps/partner_referrals/tests/test_partner_referrals.nim"
  exec "nim r deps/invoices/tests/test_connections.nim"
  exec "nim r deps/invoices/tests/test_invoice_connection_details.nim"
  exec "nim r deps/invoices/tests/test_invoices.nim"
  exec "nim r deps/invoices/tests/test_search_invoices.nim"
  exec "nim r deps/invoices/tests/test_templates.nim"
  exec "nim r deps/webhooks/tests/test_simulate_event.nim"
  exec "nim r deps/webhooks/tests/test_verify_webhook_signature.nim"
  exec "nim r deps/webhooks/tests/test_webhooks.nim"
  exec "nim r deps/webhooks/tests/test_webhooks_event_types.nim"
  exec "nim r deps/webhooks/tests/test_webhooks_events.nim"
  exec "nim r deps/webhooks/tests/test_webhooks_lookup.nim"
  exec "nim r deps/payment_experience/tests/test_web_profiles.nim"
  exec "nim r deps/payments/tests/test_authorizations.nim"
  exec "nim r deps/payments/tests/test_captures.nim"
  exec "nim r deps/payments/tests/test_find_eligible_methods.nim"
  exec "nim r deps/payments/tests/test_refunds.nim"
  exec "nim r deps/payouts/tests/test_payouts.nim"
  exec "nim r deps/payouts/tests/test_payouts_item.nim"
  exec "nim r deps/reporting/tests/test_balances.nim"
  exec "nim r deps/reporting/tests/test_transactions.nim"
  exec "nim r deps/tracking/tests/test_trackers.nim"
  exec "nim r deps/tracking/tests/test_trackers_batch.nim"
  exec "nim r deps/payment_tokens/tests/test_payment_tokens.nim"
  exec "nim r deps/payment_tokens/tests/test_setup_tokens.nim"
